const mongoose = require('mongoose');

const insightSchema = new mongoose.Schema(
  {
    student: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Student',
      required: [true, 'Student reference is required'],
    },
    summary: {
      type: String,
      required: [true, 'Summary is required'],
      trim: true,
    },
    details: {
      type: String,
      trim: true,
    },
    type: {
      type: String,
      enum: ['performance', 'attendance', 'general'],
      default: 'general',
    },
    score: {
      type: Number, // Numeric score generated by the AI prediction model (0-100)
      default: 0,
    },
    recommendation: {
      type: String,
      trim: true,
    },
  },
  {
    timestamps: true,
  }
);

insightSchema.index({ student: 1, createdAt: -1 });

module.exports = mongoose.model('Insight', insightSchema);
